global:
  # INFO, WARNING, ERROR
  log_level: ERROR
douban:
  # There could be movies that can't be accessed without logging in for multiple reasons.
  # You could log in to your account at https://movie.douban.com and use the browser's developer tool to check the cookies (Chrome: F12 - Network).
  # When the panel is enabled and after you reload the page once more, there should be a resource named "movie.douban.com", and you can find the cookies in Headers - Requested Headers.
  cookies: ''
  # The categories should be the same as the subdomains of douban.com. E.g., "movie" in https://movie.douban.com/people/user1/wish.
  categories: music;movie
  # The user domain should be the same as the user subfolder of the "people" subfolder on douban.com. E.g., "user1" in https://movie.douban.com/people/user1/wish.
  user_domain: user1;user2;user3
  # The list types should be the same as the list type subfolder of the user subfolder on douban.com. E.g., "wish" in https://movie.douban.com/people/user1/wish.
  list_types: wish;collect;do
  # Specify the start scraping date. In the format of YYYY-MM-DD or 'today' to start from today.
  start_date: 'today'
  # Specify how many days of data it should scrape. Set it to 0 if you would want to use the end_date instead.
  max_scraping_days: 0
  # Specify the end scraping date. In the format of YYYY-MM-DD or 'epoch' to set it to 1970-01-01.
  end_date: 2012-01-01
  # The start scraping page. It could be useful to skip days that are not in the scraping range specified above.
  start_page: 1
  # If the scraper should add the entries as soon as the data is scraped. Setting this to false would run the adding step after the entire in-range entries are scraped.
  # If the mode is set to 'add_from_file', you need to set this to false to force re-adding the entries.
  instant_add: true
  # Set this to 'scrape_only', 'add_from_file' or 'scrape_and_add' to suit your needs.
  mode: 'scrape_and_add'
  # It could be either the scraped user entry list '19700101_010101_user_entries_music_collect.list' or the further scraped entry details list '19700101_010101_entry_details_movie_wish.list'.
  # It would be used only if the mode is 'add_from_file'.
  list_file_path: '19700101_010101_entry_details_movie_wish.list'
# See https://wiki.servarr.com/docker-guide for the best setup recommendation
# See https://wiki.servarr.com/en/radarr for the details
radarr:
  host: localhost
  port: 7878
  url_base: ''
  https: false
  # See https://wiki.servarr.com/en/radarr/settings#security
  api_key: ''
  # Should be the same path you set for https://wiki.servarr.com/en/radarr/settings#root-folders
  rootFolderPath: "/data/media/movies"
  monitored: false
  addOptions: {searchForMovie: true}
  # Should be the index of your preferred quality profile. See https://wiki.servarr.com/en/radarr/settings#quality-profiles
  qualityProfileId: 1
  minimumAvailability: 'announced'
# See https://wiki.servarr.com/en/sonarr for the details
sonarr:
  host: localhost
  port: 8989
  url_base: ''
  https: false
  # See https://wiki.servarr.com/en/sonarr/settings#security
  api_key: ''
  # Should be the same path you set for https://wiki.servarr.com/en/sonarr/settings#root-folders
  rootFolderPath: "/data/media/tv"
  monitored: false
  addOptions : {monitor: "all", searchForCutoffUnmetEpisodes: true, searchForMissingEpisodes: true}
  # Should be the index of your preferred quality profile. See https://wiki.servarr.com/en/sonarr/settings#quality-profiles
  qualityProfileId: 1
  # Should be the index of your preferred language in the selected quality profile. See https://wiki.servarr.com/en/sonarr/settings#language-profiles
  languageProfileId : 1
  # Default series type. See all possible values on https://sonarr.tv/docs/api/ - Schemas - SeriesTypes.
  seriesType : 'Standard'
  addSeasonSubfolder: true 
  genreSubfolderPath: [
    { genre: ["电视剧","剧情"], path: '/series', seriesType: 'Standard' },
    { genre: ["动漫", "动画"], path: '/anime', seriesType: 'Anime'},
    { genre: ["纪录片"], path: '/documentaries', seriesType: 'Standard'},
    { genre: ["综艺", "真人秀"], path: '/shows', seriesType: 'Daily'}
  ]
# See https://wiki.servarr.com/en/lidarr for the details
lidarr:
  host: localhost
  port: 8686
  url_base: ''
  https: false
  # See https://wiki.servarr.com/en/lidarr/settings#security
  api_key: ''
  # Should be the same path you set for https://wiki.servarr.com/en/lidarr/settings#root-folders
  rootFolderPath: "/data/media/music"
  monitored: false
  addOptions: {addType: "automatic", searchForNewAlbum: true}
  qualityProfileId: 1
  metadataProfileId: 1